### ISSUE TITLE
TODO: Next Assignments

### ISSUE THREAD

**Issue by JohnRTitor** [JohnRTitor/Shell-Programming-Assignments#2]
We need to wrap up our pending college assignments from before the vacation.
The lists are:

- [x] Shell script to calculate consumption of electric bill

- [X] Shell script to check whether a person is eligible to vote
- [X] Calculate gross salary of a person, if base_salary > 15000, DA=30%. else DA=25%.

@Vivek-GuptaXCode Prepare commits and push to dev branch ASAP.

**Comment by Vivek-GuptaXCode** [comment]
got it, thanks for the reminder have been very busy these days

**Comment by JohnRTitor** [comment]
Great job, marked first task as done. Note that you just can directly push to dev branch, after testing we merge it to main
